# Generated by Django 4.2.16 on 2024-12-14 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Unique Student ID", max_length=20, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Christianity", "Christianity"),
                            ("Islam", "Islam"),
                            ("Hinduism", "Hinduism"),
                            ("Buddhism", "Buddhism"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(default="Filipino", max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("grade_level", models.IntegerField()),
                ("section", models.CharField(max_length=20)),
                ("admission_date", models.DateField(auto_now_add=True)),
                ("previous_school", models.CharField(blank=True, max_length=100)),
                (
                    "academic_year",
                    models.CharField(help_text="Format: YYYY-YYYY", max_length=9),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_relationship", models.CharField(max_length=50)),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("father_name", models.CharField(blank=True, max_length=100)),
                ("father_occupation", models.CharField(blank=True, max_length=100)),
                (
                    "father_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("father_email", models.EmailField(blank=True, max_length=254)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("mother_occupation", models.CharField(blank=True, max_length=100)),
                (
                    "mother_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("mother_email", models.EmailField(blank=True, max_length=254)),
                ("guardian_name", models.CharField(blank=True, max_length=100)),
                ("guardian_relationship", models.CharField(blank=True, max_length=50)),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("guardian_email", models.EmailField(blank=True, max_length=254)),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="List any medical conditions"
                    ),
                ),
                ("allergies", models.TextField(blank=True)),
                ("medications", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["grade_level", "last_name", "first_name"],
            },
        ),
    ]
