# Generated by Django 4.2.16 on 2024-12-15 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
